name = input("Enter a name: ")
age = int(input("Enter an age: "))
food = input("Enter a food: ")
place = input("Enter a place: ")
print(name, "is", age, "years old and loves eating", food, "and lives in", place)